apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app: "{{ .Values.name }}"
  annotations:
    date: "{{ now | unixEpoch }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80